# TODO FILTER BY MAJOR

# TODO LEAST SUM SQUARED WEIGHTING SO THAT SCHOOLS WITH TOO HIGH TEST SCORES ARE DIS-VALUED

# TODO WEIGHTING FOR LOCATION

# TODO WEIGHTING FOR STARTING SALARY

# TODO WEIGHTING FOR DROPOUT RATE

# TODO SOME KIND OF ANALYSIS FOR COST...?

# TODO OUTPUT SCHOOLS BY ORDER AND DESCRIPTION
